version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4943:4943"
    volumes:
      - myapp-data:/app
    command: tail -f /dev/null

volumes:
  myapp-data: {}
